name: Coveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests
        run: |
          coverage run -m pytest
          coverage report
          coverage html

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
